### ISSUE TITLE
Systemctl not found

### ISSUE THREAD

**Issue by izzatzr** [techno-express/Virtualmin#2]
I got this error when running the docker image

```virtualmin-7c4664cc9b-fnwtgvirtualmin2020-06-23 03:14:31,752 fail2ban.server [29]: INFO Starting Fail2ban v0.9.3
virtualmin-7c4664cc9b-fnwtgvirtualmin2020-06-23 03:14:31,752 fail2ban.server [29]: INFO Starting in daemon mode
virtualmin-7c4664cc9b-fnwtgvirtualminTraceback (most recent call last):
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 3162, in <module>
virtualmin-7c4664cc9b-fnwtgvirtualmin result = command_func()
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 2807, in system_default
virtualmin-7c4664cc9b-fnwtgvirtualmin self.start_system_default(init = init)
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 2814, in start_system_default
virtualmin-7c4664cc9b-fnwtgvirtualmin self.start_units(default_services)
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 1280, in start_units
virtualmin-7c4664cc9b-fnwtgvirtualmin if not self.start_unit(unit):
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 1295, in start_unit
virtualmin-7c4664cc9b-fnwtgvirtualmin return self.start_unit_from(conf)
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 1317, in start_unit_from
virtualmin-7c4664cc9b-fnwtgvirtualmin run = subprocess_wait(sudo+newcmd, env)
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/bin/systemctl", line 410, in subprocess_wait
virtualmin-7c4664cc9b-fnwtgvirtualmin run = subprocess.Popen(cmd, shell=shell, env=env)
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
virtualmin-7c4664cc9b-fnwtgvirtualmin errread, errwrite)
virtualmin-7c4664cc9b-fnwtgvirtualmin File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
virtualmin-7c4664cc9b-fnwtgvirtualmin raise child_exception
virtualmin-7c4664cc9b-fnwtgvirtualminOSError: [Errno 2] No such file or directory```

**Comment by jaylfc** [comment]
Same here, is it related to me running Ubuntu 20.04 and it not being supported yet?

**Comment by Peelige** [comment]
Same issue here.  Shame as this looks to be the defacto virtualmin image to use.
